### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by Ngocleeeeee**

### CODE REVIEW

**Comment by Ngocleeeeee** [comment]
update nettruyen

**Comment by vetleledaal** [comment]
Wrong repo, and the domain you used is a copycat

keiyoushi/extensions-source#2887

**Comment by Karutovn** [comment]
> update

Just waiting bro (nettruyen don't have notifications including translator)

**Comment by Kiki88x** [comment]
Im sorry excuse me, i wan to ask... My extension becomes like this after update extension
Screenshot_20240518-020919
Where should i report this? Extension Web name: Anchira.to

**Comment by Karutovn** [comment]
> Im sorry excuse me, i wan to ask... My extension becomes like this after update extension
> Screenshot_20240518-020919
> Where should i report this? Extension Web name: Anchira.to

The issuse can report in [keiyoushi/extension-source](https://github.com/keiyoushi/extensions-source) and any change on code in that

**Pull request closed without merging**
